### ISSUE TITLE
Use company

### ISSUE THREAD

**Issue by reactormonk** [reactormonk/nim-mode#12]
`company` is the new hotness for autocompletion.

**Comment by mijoharas** [comment]
:+1:

**Comment by pigmej** [comment]
+1

**Comment by filcuc** [comment]
+1

**Comment by reactormonk** [comment]
I now have code for company, but while nimsuggest is still broken https://github.com/Araq/Nim/issues/2694 I don't really see a reason to merge it.

**Comment by filcuc** [comment]
Well done!! Can't wait to test it
Il 12/mag/2015 15:51, "reactormonk" <notifications@github.com> ha scritto:

**Comment by reactormonk** [comment]
Ok, issue solved. However, I can't get it to run correctly, I think I'm not using company correctly. If someone wants to help, the code is on the branch epc. To get it running, compile `nimsuggest` in the compiler tree (under `compiler/nimsuggest/nimsuggest.nim`), copy it to `bin/nimsuggest` and set `nim-nimsuggest-path` to the path of `nimsuggest`.

**Comment by pigmej** [comment]
@reactormonk 

Probably one of the cleanest implementations: https://github.com/proofit404/company-anaconda/blob/master/company-anaconda.el

Then just `(add-to-list 'company-backends 'company-XXX)`

**Comment by reactormonk** [comment]
Thanks to @pigmej, should work now.
