### ISSUE TITLE
Get this into MELPA to replace the nimrod-mode from 2011

### ISSUE THREAD

**Issue by russel** [reactormonk/nim-mode#9]
Emacs 24 packages list a nimrod-mode from 2011 (which doesn't appear to work). This mode needs installing to MELPA so that it can be accessed via packaging.

**Comment by reactormonk** [comment]
https://github.com/milkypostman/melpa/pull/2355 Naturally, you will need to reinstall the package because of the name change.

**Comment by reactormonk** [comment]
No need to reinstall.

**Comment by russel** [comment]
Works fine for me :-)

However I guess I should continue to use the Git repository directly in case of making pull requests.
